server:
  port: 10242
spring:
  application:
    name: tentwelve-serviser-manage-article
  datasource:
    name: db_cldiscuss
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.105.194.180:3306/db_cldiscuss?characterEncoding=utf-8
    username: root
    password: cenliu...3306
    driverClassName: com.mysql.jdbc.Driver